from pathlib import Path

p=Path('src/Aog/Dispatcher.php')
s=p.read_text(encoding='utf-8')
old_gget="    private function gget(array $form): string\n    {$pcuid=(string)($form['pcuid']??'GUEST');$match=$this->db->getMatch($pcuid)??['gmode'=>1,'taku'=>0,'seats'=>4,'tid'=>1,'pindex'=>0,'mid'=>1,'name'=>'ゲスト','state'=>'matching','table'=>Table::create(0,0)];$must=$this->must($form);$ready=((string)($form['ready']??''))==='1';$nextSno=(int)($form['next_sno']??($must[5]??0));$table=new Table(is_array($match['table']??null)?$match['table']:Table::create((int)$match['taku'],0));if($ready&&(($match['state']??'')==='matching')){$table->startKyoku();$match['state']='playing';}if($ready)$table->flushPending();$match['table']=$table->state();$this->db->saveMatch($pcuid,$match);return $this->xml('<game><all_ready>'.($ready?1:0).'</all_ready>'.$this->matchingXml($match).($ready?$table->cellsFrom($nextSno):'').'</game>');}"
new_gget="    private function gget(array $form): string\n    {$pcuid=(string)($form['pcuid']??'GUEST');$match=$this->db->getMatch($pcuid)??['gmode'=>1,'taku'=>0,'seats'=>4,'tid'=>1,'pindex'=>0,'mid'=>1,'name'=>'ゲスト','state'=>'matching','table'=>Table::create(0,0)];$must=$this->must($form);$ready=((string)($form['ready']??''))==='1';$tid=(int)($must[2]??$match['tid']??1);$nextSno=(int)($form['next_sno']??($must[5]??0));$chatSince=(int)($must[6]??0);$table=new Table(is_array($match['table']??null)?$match['table']:Table::create((int)$match['taku'],0));if($ready&&(($match['state']??'')==='matching')){$table->startKyoku();$match['state']='playing';}if($ready)$table->flushPending();$match['table']=$table->state();$this->db->saveMatch($pcuid,$match);$chat=(new MiscDispatcher($this->db))->stampXml('chat',$tid,$chatSince);return $this->xml('<game><all_ready>'.($ready?1:0).'</all_ready>'.$this->matchingXml($match).($ready?$table->cellsFrom($nextSno):'').'</game>'.$chat);}"
if old_gget not in s: raise SystemExit('gget anchor missing')
s=s.replace(old_gget,new_gget,1)
old_gpost="    private function gpost(array $form): string\n    {$pcuid=(string)($form['pcuid']??'GUEST');$match=$this->db->getMatch($pcuid);if(!$match)return $this->xml('<game><taikyoku><cell_info available=\"0\" /></taikyoku></game>');$must=$this->must($form);$kind=(int)($form['kind']??($must[6]??0));$pindex=(int)($form['pindex']??($must[3]??0));$pai=(int)($form['pai']??($must[9]??0));$tepaiId=(int)($form['tepai_id']??($must[10]??0));$tepaiId2=(int)($form['tepai_id2']??($must[11]??0));$reach=(int)($form['reach']??($must[12]??0));$tsumogiri=(int)($form['tsumogiri']??($must[13]??0));$table=new Table(is_array($match['table']??null)?$match['table']:Table::create((int)$match['taku'],0));$before=count($table->state()['cells']??[]);$table->onCommand($kind,$pindex,$pai,$reach,$tsumogiri,$tepaiId,$tepaiId2);$table->flushPending();$match['table']=$table->state();$this->db->saveMatch($pcuid,$match);return $this->xml('<game>'.$table->cellsFrom($before).'</game>');}"
new_gpost="    private function gpost(array $form): string\n    {$pcuid=(string)($form['pcuid']??'GUEST');$match=$this->db->getMatch($pcuid);if(!$match)return $this->xml('<game><taikyoku><cell_info available=\"0\" /></taikyoku></game><chat></chat>');$must=$this->must($form);$tid=(int)($must[2]??$match['tid']??1);$kind=(int)($form['kind']??($must[6]??0));$pindex=(int)($form['pindex']??($must[3]??0));$pai=(int)($form['pai']??($must[9]??0));$tepaiId=(int)($form['tepai_id']??($must[10]??0));$tepaiId2=(int)($form['tepai_id2']??($must[11]??0));$reach=(int)($form['reach']??($must[12]??0));$tsumogiri=(int)($form['tsumogiri']??($must[13]??0));$table=new Table(is_array($match['table']??null)?$match['table']:Table::create((int)$match['taku'],0));$before=count($table->state()['cells']??[]);$table->onCommand($kind,$pindex,$pai,$reach,$tsumogiri,$tepaiId,$tepaiId2);$table->flushPending();$match['table']=$table->state();$this->db->saveMatch($pcuid,$match);$chat=(new MiscDispatcher($this->db))->stampXml('chat',$tid,1000000000);return $this->xml('<game>'.$table->cellsFrom($before).'</game>'.$chat);}"
if old_gpost not in s: raise SystemExit('gpost anchor missing')
s=s.replace(old_gpost,new_gpost,1)
p.write_text(s,encoding='utf-8')
